import React, { useState, useEffect } from 'react';
import { GitCommit, X, Check, ArrowUp, Github, Loader2, File, CheckSquare, Square, GitBranch, ChevronDown } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import { API_BASE } from '../../services/api';

interface CommitModalProps {
  isOpen: boolean;
  onClose: () => void;
  projectPath: string;
  onCommitSuccess?: () => void;
}

const CommitModal = ({ isOpen, onClose, projectPath, onCommitSuccess }: CommitModalProps) => {
  const [message, setMessage] = useState('');
  const [isCommitting, setIsCommitting] = useState(false);
  const [stage, setStage] = useState<'draft' | 'committing' | 'pushing' | 'pr' | 'success'>('draft');
  const [stats, setStats] = useState({ files: 0, added: 0, removed: 0 });
  const [files, setFiles] = useState<any[]>([]);
  const [selectedFiles, setSelectedFiles] = useState<Set<string>>(new Set());
  const [currentBranch, setCurrentBranch] = useState('main');

  useEffect(() => {
    if (isOpen) {
      // Fetch branch info
      fetch(`${API_BASE}/api/git/branches?projectPath=${encodeURIComponent(projectPath)}`)
        .then(res => res.json())
        .then(data => setCurrentBranch(data.current || 'main'))
        .catch(console.error);

      // Fetch diff stats and files
      fetch(`${API_BASE}/api/git/diff?projectPath=${encodeURIComponent(projectPath)}`)
        .then(res => res.json())
        .then(data => {
          if (data.status === 'success') {
            setStats({
              files: data.files.length,
              added: data.added,
              removed: data.removed
            });
            setFiles(data.files);
            // Select all by default
            setSelectedFiles(new Set(data.files.map((f: any) => f.path)));
          }
        })
        .catch(console.error);
    }
  }, [isOpen, projectPath]);

  const toggleFile = (path: string, e?: React.MouseEvent) => {
    e?.stopPropagation();
    const newSelected = new Set(selectedFiles);
    if (newSelected.has(path)) {
      newSelected.delete(path);
    } else {
      newSelected.add(path);
    }
    setSelectedFiles(newSelected);
  };

  const toggleAll = (e?: React.MouseEvent) => {
    e?.stopPropagation();
    if (selectedFiles.size === files.length && files.length > 0) {
      setSelectedFiles(new Set());
    } else {
      setSelectedFiles(new Set(files.map(f => f.path)));
    }
  };

  const [isGenerating, setIsGenerating] = useState(false);
  
  // Auto-generate commit message when selection changes
  useEffect(() => {
    if (!isOpen || selectedFiles.size === 0) return;

    const timer = setTimeout(async () => {
      setIsGenerating(true);
      try {
        const res = await fetch(`${API_BASE}/api/git/generate-message`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            projectPath,
            files: Array.from(selectedFiles)
          })
        });
        
        if (res.ok) {
          const data = await res.json();
          if (data.message) setMessage(data.message);
        }
      } catch (err) {
        console.error('Failed to generate commit message', err);
      } finally {
        setIsGenerating(false);
      }
    }, 1000); // 1s debounce

    return () => clearTimeout(timer);
  }, [selectedFiles, isOpen, projectPath]);

  const handleCommit = async (action: 'commit' | 'push' | 'pr') => {
    if (selectedFiles.size === 0) return;
    
    setIsCommitting(true);
    setStage(action === 'commit' ? 'committing' : action === 'push' ? 'pushing' : 'pr');

    try {
      // 1. Commit
      const commitRes = await fetch(`${API_BASE}/api/git/commit`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ 
          path: projectPath, 
          message: message || `chore: update ${selectedFiles.size} files`,
          files: Array.from(selectedFiles),
          push: action === 'push' || action === 'pr'
        })
      });

      if (!commitRes.ok) throw new Error('Commit failed');

      // 2. Create PR if requested
      if (action === 'pr') {
        const prRes = await fetch(`${API_BASE}/api/git/pr`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ path: projectPath, title: message, body: 'Generated by Queen Bee' })
        });
        if (!prRes.ok) throw new Error('PR creation failed');
      }

      setStage('success');
      setTimeout(() => {
        onClose();
        if (onCommitSuccess) onCommitSuccess();
        setStage('draft');
        setMessage('');
        setIsCommitting(false);
      }, 1000);

    } catch (error) {
      console.error(error);
      setIsCommitting(false);
      setStage('draft');
      alert('Action failed. Check console.');
    }
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/40 backdrop-blur-md p-4">
      <motion.div 
        initial={{ opacity: 0, scale: 0.95, y: 20 }}
        animate={{ opacity: 1, scale: 1, y: 0 }}
        exit={{ opacity: 0, scale: 0.95, y: 20 }}
        className="bg-white rounded-3xl shadow-2xl w-full max-w-lg overflow-hidden flex flex-col max-h-[90vh] border border-zinc-200"
      >
        {/* Header */}
        <div className="px-6 py-5 border-b border-zinc-100 flex items-center justify-between bg-white">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-2xl bg-zinc-900 flex items-center justify-center shadow-lg shadow-black/20">
              <GitCommit size={20} className="text-white" />
            </div>
            <div>
                <h2 className="text-lg font-black text-zinc-900 uppercase tracking-tight">Commit Changes</h2>
                <p className="text-[10px] font-bold text-zinc-400 uppercase tracking-widest">Staging Area & Controls</p>
            </div>
          </div>
          <button onClick={onClose} className="p-2 hover:bg-zinc-100 rounded-xl text-zinc-400 hover:text-zinc-900 transition-all">
            <X size={20} />
          </button>
        </div>

        {/* Content */}
        <div className="p-6 bg-zinc-50/30 flex-1 overflow-y-auto space-y-6">
          <div className="flex justify-between items-start">
            <div className="space-y-1">
              <span className="text-[10px] font-black text-zinc-400 uppercase tracking-widest">Active Branch</span>
              <div className="flex items-center gap-2 px-3 py-1.5 bg-white border border-zinc-200 rounded-xl shadow-sm text-zinc-900 font-bold text-xs">
                <GitBranch size={12} className="text-blue-500" />
                <span>{currentBranch}</span>
              </div>
            </div>
            <div className="text-right space-y-1">
              <div className="text-[10px] font-black text-zinc-400 uppercase tracking-widest">Change Summary</div>
              <div className="text-xs font-bold">
                <span className="text-zinc-900">{selectedFiles.size} / {files.length} files selected</span>
                <span className="mx-2 text-zinc-200">|</span>
                <span className="text-emerald-600 font-black">+{stats.added}</span>
                <span className="ml-1 text-rose-600 font-black">-{stats.removed}</span>
              </div>
            </div>
          </div>

          <div className="space-y-3">
            <div className="flex items-center justify-between">
                <label className="text-[10px] font-black text-zinc-400 uppercase tracking-widest ml-1">Staged Files</label>
                <button 
                    onClick={toggleAll}
                    className="text-[10px] font-black text-blue-600 uppercase tracking-widest hover:text-blue-700 transition-colors bg-blue-50 px-2 py-1 rounded-md border border-blue-100"
                >
                    {selectedFiles.size === files.length ? 'Unselect All' : 'Select All'}
                </button>
            </div>
            
            <div className="bg-white border border-zinc-200 rounded-2xl overflow-hidden shadow-sm">
                <div className="max-h-64 overflow-y-auto">
                    {files.length === 0 ? (
                        <div className="p-10 text-center text-xs text-zinc-400 italic">No changes detected in worktree.</div>
                    ) : (
                        files.map(file => (
                            <div 
                                key={file.path}
                                onClick={(e) => toggleFile(file.path, e)}
                                className={`group px-4 py-3 flex items-center gap-3 cursor-pointer border-b border-zinc-50 last:border-0 transition-all ${selectedFiles.has(file.path) ? 'bg-blue-50/30' : 'hover:bg-zinc-50'}`}
                            >
                                <div className={`w-5 h-5 rounded-lg flex items-center justify-center border transition-all ${
                                    selectedFiles.has(file.path) ? 'bg-zinc-900 border-zinc-900 text-white shadow-md' : 'bg-white border-zinc-300'
                                }`}>
                                    {selectedFiles.has(file.path) && <Check size={12} strokeWidth={4} />}
                                </div>
                                <File size={14} className={selectedFiles.has(file.path) ? 'text-blue-500' : 'text-zinc-400'} />
                                <div className="flex-1 min-w-0">
                                    <div className={`text-[11px] font-bold truncate ${selectedFiles.has(file.path) ? 'text-zinc-900' : 'text-zinc-600'}`}>
                                        {file.path.split('/').pop()}
                                    </div>
                                    <div className="text-[9px] text-zinc-400 truncate font-medium">{file.path}</div>
                                </div>
                                <div className="text-[10px] font-mono font-black flex gap-2">
                                    <span className="text-emerald-600">+{file.stats.added}</span>
                                    <span className="text-rose-600">-{file.stats.removed}</span>
                                </div>
                            </div>
                        ))
                    )}
                </div>
            </div>
          </div>

          <div className="space-y-2">
            <div className="flex items-center justify-between">
                <label className="text-[10px] font-black text-zinc-400 uppercase tracking-widest ml-1">Commit Message</label>
                {isGenerating && (
                    <div className="flex items-center gap-1 text-[10px] font-bold text-blue-500 uppercase tracking-widest animate-pulse">
                        <Loader2 size={10} className="animate-spin" />
                        Generating...
                    </div>
                )}
            </div>
            <textarea
              value={message}
              onChange={(e) => setMessage(e.target.value)}
              placeholder={`Describe the changes in these ${selectedFiles.size} files...`}
              className="w-full px-4 py-3 bg-white border border-zinc-200 rounded-2xl text-sm font-medium text-zinc-900 focus:border-blue-500 focus:ring-4 focus:ring-blue-500/5 transition-all resize-none h-24 shadow-sm"
            />
          </div>
        </div>

        {/* Footer Actions */}
        <div className="p-4 bg-white border-t border-zinc-100 flex flex-col gap-2">
           <div className="grid grid-cols-2 gap-2">
                <button 
                  onClick={() => handleCommit('commit')}
                  disabled={isCommitting || selectedFiles.size === 0}
                  className="flex items-center justify-center gap-2 py-3 bg-zinc-100 hover:bg-zinc-200 text-zinc-900 font-bold rounded-xl transition-all disabled:opacity-50"
                >
                  {stage === 'committing' ? <Loader2 size={16} className="animate-spin" /> : <GitCommit size={16} />}
                  <span>Just Commit</span>
                </button>
                <button 
                  onClick={() => handleCommit('push')}
                  disabled={isCommitting || selectedFiles.size === 0}
                  className="flex items-center justify-center gap-2 py-3 bg-zinc-900 hover:bg-zinc-800 text-white font-bold rounded-xl transition-all shadow-lg disabled:opacity-50"
                >
                  {stage === 'pushing' ? <Loader2 size={16} className="animate-spin" /> : <ArrowUp size={16} />}
                  <span>Commit & Push</span>
                </button>
           </div>
           <button 
              onClick={() => handleCommit('pr')}
              disabled={isCommitting || selectedFiles.size === 0}
              className="flex items-center justify-center gap-2 py-3 border border-zinc-200 hover:bg-zinc-50 text-zinc-600 font-bold rounded-xl transition-all disabled:opacity-50"
            >
              <Github size={16} />
              <span>Create Pull Request</span>
            </button>
        </div>

        <AnimatePresence>
            {stage === 'success' && (
                <motion.div 
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    exit={{ opacity: 0 }}
                    className="absolute inset-0 bg-white/90 backdrop-blur-sm flex flex-col items-center justify-center z-[110]"
                >
                    <div className="w-16 h-16 rounded-full bg-emerald-500 flex items-center justify-center text-white shadow-2xl shadow-emerald-200 mb-4">
                        <Check size={32} strokeWidth={3} />
                    </div>
                    <h3 className="text-xl font-black text-zinc-900 uppercase tracking-tight">Changes Committed!</h3>
                    <p className="text-sm font-bold text-zinc-400 mt-1 uppercase tracking-widest">Repository is clean.</p>
                </motion.div>
            )}
        </AnimatePresence>
      </motion.div>
    </div>
  );
};

export default CommitModal;